blank_issues_enabled: false
contact_links:
  - name: Me
    email: contact@kerryghan.dev
    about: If you just want to say hi, or have any questions about the project, feel free to reach out!
    link: https://kerryghan.dev
